"""review optimal space class

Revision ID: 6084039aa3b0
Revises: 358fa2cced6c
Create Date: 2026-10-05 01:24:11.616941
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6084039aa3b0"
down_revision: str | None = "358fa2cced6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("optimal_space_class", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "optimal_space_class")
    # ### end Alembic commands ###
