"""submission statement and review completion

Revision ID: 358fa2cced6c
Revises: 5a6b74ed110f
Create Date: 2026-10-05 00:34:17.550980
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "358fa2cced6c"
down_revision: str | None = "5a6b74ed110f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("served_model", sa.String(length=100), nullable=True))
    op.add_column("reviews", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("submissions", sa.Column("statement", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "statement")
    op.drop_column("reviews", "completed_at")
    op.drop_column("reviews", "served_model")
    # ### end Alembic commands ###
