"""chat message streaming state

Revision ID: c8c90bccbbae
Revises: 6084039aa3b0
Create Date: 2026-10-05 01:49:50.532941
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c8c90bccbbae"
down_revision: str | None = "6084039aa3b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
    )
    op.add_column(
        "chat_messages",
        sa.Column(
            "status",
            sa.Enum(
                "streaming",
                "done",
                "failed",
                name="chatmessagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
    )
    op.add_column("chat_messages", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("chat_messages", sa.Column("provider", sa.String(length=32), nullable=True))
    op.add_column("chat_messages", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("chat_messages", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_chat_messages_seq"), "chat_messages", ["seq"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_seq"), table_name="chat_messages")
    op.drop_column("chat_messages", "output_tokens")
    op.drop_column("chat_messages", "input_tokens")
    op.drop_column("chat_messages", "provider")
    op.drop_column("chat_messages", "error")
    op.drop_column("chat_messages", "status")
    op.drop_column("chat_messages", "seq")
    # ### end Alembic commands ###
